chore: update all secrethub with keeper command
gravitee-io/gravitee-ui-particles pull request #117
Opened 2022-03-29 11:01 UTC by sursak123

chore: update all secrethub with keeper command

secrethub orb will not be used any more and has to be replaced with keeper

**Description**

Updated keeper orb and keeper urls in the jobs

**Additional context**

2022-03-29 11:02 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.3.1-cicd-secrethub-to-keeper-f2532c3
# or
yarn add @gravitee/ui-policy-studio-angular@3.3.1-cicd-secrethub-to-keeper-f2532c3
```

2022-03-29 11:02 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.3.1-cicd-secrethub-to-keeper-f2532c3
# or
yarn add @gravitee/ui-particles-angular@3.3.1-cicd-secrethub-to-keeper-f2532c3
```

2022-03-30 09:59 UTC, gaetanmaisse commented on .circleci/config.yml
> +
We need to remove the extra space

2022-04-04 08:08 UTC, gaetanmaisse requested changes

2022-04-04 08:08 UTC, gaetanmaisse commented on .circleci/config.yml
> +
@sursak123 can you please update your IDE to not add these extra spaces and remove them from your commit?

2022-04-11 09:08 UTC, gaetanmaisse approved these changes

2022-04-11 09:11 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-particles-angular@3.3.1-cicd-secrethub-to-keeper-1a50e8a
# or
yarn add @gravitee/ui-particles-angular@3.3.1-cicd-secrethub-to-keeper-1a50e8a
```

2022-04-11 09:11 UTC, graviteeio commented
**Gravitee.io Automatic Deployment**
A prerelease version of this package has been published! 🚀
To use it in your project run the following lines:
```shell
npm install @gravitee/ui-policy-studio-angular@3.3.1-cicd-secrethub-to-keeper-1a50e8a
# or
yarn add @gravitee/ui-policy-studio-angular@3.3.1-cicd-secrethub-to-keeper-1a50e8a
```

2022-04-11 09:21 UTC, merged

2022-04-13 09:45 UTC, graviteeio commented
:tada: This PR is included in version 3.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gravitee/ui-particles-angular/v/3.4.0)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@gravitee/ui-policy-studio-angular/v/3.4.0)
- [GitHub release](https://github.com/gravitee-io/gravitee-ui-particles/releases/tag/v3.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: